import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/redux/redux-provider";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar /> 
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
